jobs:
- name: run-cdcs
  plan:
  - get: git
    trigger: true
  - load_var: consumers
    file: git/consumers.json
  - across:
    - var: consumer
      values: ((.:consumers))
      max_in_flight: all
    fail_fast: true
    task: ((.:consumer))
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
      run:
        path: sleep
        args: ["60"]

resources:
- check_every: 10m
  name: git
  source:
    branch: main
    uri: https://github.com/simonjohansson/concourse-across-test.git
  type: git